prgrms-fe-devcourse/NFE1_2_2_MUX

src/auth/Dashboard.jsx
src/components/UserCard.jsx
src/components/UserProfile.jsx
src/utils/api.js

- 더미 데이터를 사용하게끔 코딩되어 있는 부분을 실제 api 활용 코드로 변경
- UserProfile 코드 변경
- UserCard 코드 변경
- 더미 데이터를 삭제하고 api를 활용하여 유저 데이터를 끌어오는 것으로 변경하였습니다.
- close #58

[feat] 기존 유저 컴포넌트를 더미 데이터 활용에서 api 활용으로 변경

---

src/App.jsx
src/auth/Dashboard.jsx
src/auth/Login.jsx
src/components/modals/ProfileEditModal.jsx
src/components/modals/UpdatePasswordModal.jsx
src/utils/api.js

- 비밀번호를 변경할 수 있는 모달을 구현
- 비밀번호를 변경할 수 있게 함.
- 토큰으로 인증된 사용자만 접근 가능
- 현재 정보수정 모달안에 서브모달로 구현 완료 되었습니다!
- 다만 현재 비밀번호를 입력받고 비교하는 건 api가 따로 있어야해서 구현하지 못할 것 같습니다 :(
- close #32

[feat] 비밀번호 변경 기능 구현

---

src/auth/Signup.jsx

- 회원가입 시 보안 수준 규칙 적용
- 비밀번호는 최소 8자 이상이어야 한다
- 비밀번호에는 대문자가 최소 1자 포함되어야 한다
- 비밀번호에는 숫자가 최소 1자 포함되어야 한다
- 비밀번호에는 특수문자가 최소 1자 포함되어야 한다
- 위의 조건을 충족하지 못할 시 붉은 글씨로 경고
- 
- close #29

[feat] 회원가입 시 보안 수준 규칙 적용

---

src/components/UserProfile.jsx
src/components/modals/NotificationModal.jsx

- fullName 파싱 오류 해결
- fullName이 문자열인지 확인: 
: UserProfilefullName && typeof fullName === 'string' 조건을 추가하여 fullName이 유효한 JSON 문자열일 때만 파싱하도록 했습니다.
- close #85

[fix] fullName 파싱 오류 해결

---

src/components/PostCard.jsx
src/pages/PostFeed/PostFeed.jsx

- PostCard에서 재생/ 일시정지 되도록 기능 변경
- 재사용 했을 때, 프로필 이미지 페이지 에서도 재생이 가능하게 변경
- PostCard를 누르면 여전히 노래가 재생됨.
- PostCard 자체에서 재생 / 일시정지를 관리하기 때문에, 다른 페이지에서 id값만 잘 받오면 똑같이 재생이 잘 되도록 구현.
- 원래 일시정지가 안되었었는데, 한 번 더 누르면 일시정지가 잘 되도록 구현.
- 프로필 페이지에서도 노래가 잘 나오는거 확인했습니다!
- 아직 재생플레이어가 설정 안돼서 다른 페이지 가면 노래가 끊깁니다!
- close #84

[Feat]: PostCard에서 음악을 재생/일시정지 하도록 변경

---

src/components/UserCard.jsx
src/components/UserProfile.jsx

- 기능 내용 요약 설명
- 구현 내용 1
- 구현 내용 2
- 이미지 첨부 (선택)
- close #이슈번호

[fix] UserCard, UserProfile 파싱오류 해결

---

src/components/PostCard.jsx
src/pages/PostFeed/PostFeed.jsx

- PostCard에서 모달창이 열리도록 수정하였습니다.
- 다른 페이지에서 재사용 할 경우, 마찬가지로 모달창이 뜰 수 있도록 구현하였습니다.
- 프로필 페이지에서도 정상적으로 모달창이 열리도록 구현하였습니다.
- close #90

[Feat] PostCard에서 모달창 열리게 기능 수정

---

src/components/CurationCard.jsx

- 유튜브 뮤직에서 인기곡으로 음악 데이터 갖고오는 기능 구현
- youtube-music api를 통해 인기곡을 불러오게끔 구현하였습니다.
- 구현 하지 않은 내용 있으면 comment 부탁드립니다!
- 버그 생길 시 바로 말씀해주시면 확인 후 fix올리겠습니다!
- close #63

[feat]: CurationCard 컴포넌트에 API 연결 기능 구현

---

src/components/CurationCard.jsx
src/components/PostCard.jsx
src/components/UserProfile.jsx

- 카드 컴포넌트 크기 변경
- 포스트 카드 크기 축소
- 큐레이션 카드 크기 확대
- 유저 프로필 카드 크기 확대
- close #44

[Feat] 카드 컴포넌트 카드 크기 변경

---

src/components/ArtistCard.jsx
src/components/CurationCard.jsx

- api연결을 통해 해당 카드에 작성자 이름, 이미지, 음원 파일 연결
- 프로그래머스 api 연결 기능 구현
-  해상도 분기점 구현
- 미구현 부분있거나 오류 있으면 comment 남겨주세요!
- close #18

[feat]: ArtistCard 컴포넌트에 API 연결 기능 구현

---

src/components/PostCard.jsx

- 스타일 재수정
- 포스트 카드 스타일 재수정
- close #이슈번호

[Fix] 최종 포스트카드 디자인과 다른 기능 재적용

---

src/App.jsx
src/components/ArtistCard.jsx
src/components/CurationCard.jsx
src/components/modals/PostUpload.jsx
src/components/modals/TrackUpload.jsx
src/components/modals/UploadModal.jsx
src/pages/Curation-Artist/CurationArt.jsx

- 아티스트, 큐레이션 리스트를 나열하는 페이지 구현
- 큐레이션 리스트 나열 부분 기능 구현
- 아티스트 리스트 나열 부분 기능 구현
- 오류나 수정할 부분 있으면 comment 남겨주세요!
- close #17

[feat]: curation-artist 페이지 구현

---

src/components/main/Navigation.jsx
src/components/modals/NotificationModal.jsx
src/profile/ProfilePage.jsx

- 새로운 알림이 도착하면 알림 아이콘에 도트가 찍힌다.
- 모달을 열면 도트가 사라지고 새로운 알림이 도착하면 도트가 생성된다.
- close #106

[feat] 네비게이션의 알림 아이콘에 도트 표시

---

src/components/ArtistCard.jsx
src/pages/Curation-Artist/CurationArt.jsx

- 아티스트 카드 단일 컴포넌트로 기능 구현하였습니다.
- 아티스트-큐레이션 페이지 수정하였습니다.
- 해상도 분기점 잡아놓았습니다.
- 오류 있거나 수정할 부분 있으면 comment남겨주세요!
- close #17

[feat]: 아티스트 카드 단일 컴포넌트로 기능 구현

---

src/auth/Dashboard.jsx
src/components/HorizontalArtistCard.jsx
src/profile/ProfilePage.jsx

- 가로형 아티스트음원 컴포넌트 제작
- 프로필 페이지에 적용
- 가로형 컴포넌트 구현하였습니다.
- 프로필 페이지에 기존 음원 카드 대신 가로형 컴포넌트로 대체하였습니다.
- close #118

[Feat] 가로형 컴포넌트 구현 및 프로필 페이지에 설정

---

src/App.jsx
src/auth/Login.jsx
src/components/main/Navigation.jsx
src/profile/ProfilePage.jsx

- 페이지 전체적인 라우터 설정
- close #117

[feat]: 라우터 설정

---

src/App.jsx
src/components/main/Navigation.jsx
src/pages/LandingPage/LandingPage.jsx

- 랜딩페이지 반응형과 auth 상단에 네비게이션 보이는 부분 수정 및 색상 조정
-  랜딩페이지 반응형 수정
- auth 상단에 네비게이션 보이는 부분 수정
- 네비게이션 색상 조정
- close #122

[fix] 랜딩페이지 반응형 및 네비게이션 수정

---

src/App.jsx
src/auth/Login.jsx
src/auth/Signup.jsx
src/pages/LandingPage/LandingPage.jsx

- 네비게이션 숨기기, 로그인, 회원가입 배경 색 조정
- 네비게이션 숨기기
- 로그인, 회원가입 배경색 조정
- close #122

[fix] 네비게이션 숨기기, 로그인, 회원가입 배경 색 조정

---

src/profile/ProfilePage.jsx

- 유저페이지 레이아웃 수정
- 프로필 영역 레이아웃 수정
- 버튼 호버 효과
fix #122

[fix] 마이페이지 수정

---

src/auth/Login.jsx
src/profile/ProfilePage.jsx

- 로그인 실패 문구 표시
- 로그인에 실패하면 '로그인에 실패하였습니다. 이메일과 비밀번호를 확인해주세요.' 라는 문구 출력
- close #122

[feat] 로그인 실패 문구 표시

---

src/components/HorizontalArtistCard.jsx
src/profile/ProfilePage.jsx

- 프로필 페이지에서 게시글 삭제 가능하도록 구현
- 프로필 상세 모달에서 게시글 정상적으로 삭제되도록 구현
- 아티스트 음원 상세 모달에서 게시글 정상적으로 삭제되도록 구현
- close #130

[feat]: 프로필페이지에서 게시글 삭제 가능하도록 기능 구현
